CREATE TABLE dealer_ordering_analysis (
  customer_name VARCHAR(255) PRIMARY KEY,
  mean_interval DECIMAL(10,2),
  median_interval DECIMAL(10,2),
  mode_interval INT,
  standard_deviation DECIMAL(10,2),
  coefficient_variation DECIMAL(10,2),
  count INT,
  total_days_covered INT,
  last_order_date DATE,
  q1_interval INT,
  q3_interval INT,
  iqr INT,
  short_interval_count INT,
  short_interval_percentage DECIMAL(10,2),
  long_interval_count INT,
  long_interval_mean DECIMAL(10,2),
  long_interval_stddev DECIMAL(10,2),
  max_similar_interval_run INT,
  avg_run_length DECIMAL(10,2),
  regularity_score DECIMAL(10,2),
  prediction_reliability DECIMAL(10,2),
  basic_category VARCHAR(255),
  refined_category VARCHAR(255),
  reminder_attempts INT,
  last_reminder_sent DATE,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
